// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gymfit.Data;

#nullable disable

namespace gymfit.Migrations
{
    [DbContext(typeof(GymFitContext))]
    [Migration("20260528122507_AddImageUrlToSportClass")]
    partial class AddImageUrlToSportClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gymfit.Models.ClassBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("ClassBooking");
                });

            modelBuilder.Entity("gymfit.Models.ClassSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SportClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SportClassId");

                    b.ToTable("ClassSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2026, 5, 7, 11, 0, 0, 0, DateTimeKind.Utc),
                            SportClassId = 1,
                            StartTime = new DateTime(2026, 5, 7, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(2026, 5, 8, 19, 0, 0, 0, DateTimeKind.Utc),
                            SportClassId = 2,
                            StartTime = new DateTime(2026, 5, 8, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new DateTime(2026, 5, 9, 15, 0, 0, 0, DateTimeKind.Utc),
                            SportClassId = 3,
                            StartTime = new DateTime(2026, 5, 9, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("gymfit.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Membership");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationDays = 30,
                            Name = "Abonament Matinal",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 2,
                            DurationDays = 30,
                            Name = "Abonament Full",
                            Price = 220.00m
                        });
                });

            modelBuilder.Entity("gymfit.Models.SportClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("SportClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Relax",
                            Name = "Yoga",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Antrenament intens pentru forță și mobilitate",
                            Name = "Functional Training",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Creștere musculară și antrenament cu greutăți",
                            Name = "Bodybuilding",
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mobilitate, stretching și recuperare",
                            Name = "Mobility & Stretch",
                            TrainerId = 2
                        });
                });

            modelBuilder.Entity("gymfit.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("gymfit.Models.UserMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MembershipId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMembership");
                });

            modelBuilder.Entity("gymfit.Models.Admin", b =>
                {
                    b.HasBaseType("gymfit.Models.User");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 99,
                            Email = "admin@gymfit.com",
                            Name = "System Admin",
                            PasswordHash = "WNSSXaLpb4cW3Li27kXDLURVomMPCskCmqDJFn1DA9Y="
                        });
                });

            modelBuilder.Entity("gymfit.Models.Trainer", b =>
                {
                    b.HasBaseType("gymfit.Models.User");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Trainer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "andrei.trainer@gymfit.com",
                            Name = "Andrei Popescu",
                            PasswordHash = "hash124",
                            Bio = "Fost atlet de performanță, pasionat de antrenamente funcționale.",
                            Specialization = "Functional Training"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria.trainer@gymfit.com",
                            Name = "Maria Ionescu",
                            PasswordHash = "hash456",
                            Bio = "Antrenoare certificată, specializată în yoga și mobilitate.",
                            Specialization = "Yoga & Mobility"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alex.trainer@gymfit.com",
                            Name = "Alex Dumitru",
                            PasswordHash = "hash789",
                            Bio = "Expert în bodybuilding și nutriție sportivă.",
                            Specialization = "Bodybuilding"
                        });
                });

            modelBuilder.Entity("gymfit.Models.ClassBooking", b =>
                {
                    b.HasOne("gymfit.Models.ClassSchedule", "ClassSchedule")
                        .WithMany("Bookings")
                        .HasForeignKey("ClassScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gymfit.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSchedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gymfit.Models.ClassSchedule", b =>
                {
                    b.HasOne("gymfit.Models.SportClass", "SportClass")
                        .WithMany("Schedules")
                        .HasForeignKey("SportClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportClass");
                });

            modelBuilder.Entity("gymfit.Models.SportClass", b =>
                {
                    b.HasOne("gymfit.Models.Trainer", "Trainer")
                        .WithMany("Classes")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("gymfit.Models.UserMembership", b =>
                {
                    b.HasOne("gymfit.Models.Membership", "Membership")
                        .WithMany("UserMemberships")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gymfit.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gymfit.Models.ClassSchedule", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("gymfit.Models.Membership", b =>
                {
                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("gymfit.Models.SportClass", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("gymfit.Models.Trainer", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
